### ISSUE TITLE
Haskell To Elm type generator

### ISSUE THREAD

**Issue by popara** [eeue56/haskell-to-elm#5]
Hi, 

I've started working on Haskell backend for an Elm app, and I started to get ideas how those two can work nicely together. 

Most simple idea was to actually generate Elm files from Haskell file. I am talking about type definitions.

Since this repo has an appropriate name, and you are renowned and opinionated member in Elm community, i wanted to get your feedback on the idea, and whether actually makes sense as a project to spend extra on :]

**Comment by eeue56** [comment]
Check out https://hackage.haskell.org/package/servant-elm
